from flask import session
class Books:
    def RetSBooks():
        S1=['Network Security and Cryptography',
        'Network Security and Cryptography is a textbook of immense value to professionals who would like to keep abreast of cutting edge security technologies.' 
        +', the book goes on to explore crucial topics such as vulnerabilities, application and OS security, malware' 
        +'(worms, viruses, bots), firewalls, intrusion prevention and detection, RFIDs, electronic payment, and web service security.']
        S2=['The Computer Science of Human Decisions',
        'Computers mainly work on algorithms.This book mainly teaches how the problems are overcome using the different kinds of constraints that occur in real life.'
        +'The book teaches the students how using the algorithms and proper programming techniques, one along with the help of the computer can gradually find the various questions of human beings.'
        +'The book is written in simple English so that the readers can understand the algorithms properly.']
        S3=['Digital Electronics','basic principles and concepts of digital circuits, focuses on finite state machines. These machines are characterized by a behavior that is determined by a limited and defined number of states,'
        +'the holding conditions for each state, and the branching conditions from one state to another. They only allow one transition at a time and can be divided into two components:a combinational logic circuit and a sequential logic circuit.']
        S4=['Integration of Renewable Sources of Energy','The latest tools and techniques for addressing the challenges of 21st century power generation, renewable sources and distribution systems'
        +'Written for practicing engineers, researchers and students alike, this book discusses state-of-the art mathematical and engineering tools for the modeling, simulation and control of renewable and mixed energy systems and related power electronics.']
        S5=['Space Mathematics: Math Problems Based on Space Science','Created by NASA for high school students interested in space science, this collection of worked problems covers a broad range of subjects, including mathematical aspects of NASA missions,' 
        +'computation and measurement, algebra, geometry, probability and statistics, exponential and logarithmic functions, trigonometry, matrix algebra, conic sections, and calculus.']
        S6=['A Researcher’s Guide to Aerospace Engineering','Aerospace engineering is concerned with the construction of aircrafts and spacecrafts. The two main branches of aerospace engineering are aeronautical and astronautical engineering. Aerospace engineering' 
        +'is a multidisciplinary field that encompasses theories and principles of prominent disciplines such as aerodynamics, mathematics, control engineering, materials science, etc.']
        S7=['Model-based System and Architecture Engineering','a system engineering method based on the use of models, with a focus on the collaborative definition, evaluation and exploitation of its architecture. This book describes the fundamentals of the method' 
        +'and its contribution to engineering issues such as requirements management, product line, system supervision, and integration']
        S8=['Architecture History and Theory in Reverse','This book looks at architecture history in reverse, in order to follow chains of precedents back through time to see how ideas alter the course of civilization in general and the discipline of architecture in particular.'
        +'Architecture History and Theory in Reverse includes 45 black-and-white images and will be useful to students of architecture and literature.']
        S9=['Automobile Engineering in a Week: For Learners, Engineering beginners, Bike and car lovers','Automobile engineering, along with aerospace engineering and marine engineering, is a branch of vehicle engineering, incorporating elements of mechanical,' 
        +'electrical, electronic, software and safety engineering as applied to the design, manufacture and operation of motorcycles, automobiles and trucks and their respective engineering subsystems.t also includes modification of vehicles.  Objective of the book is to understand'
        +'the construction and working principle of various parts of an automobile.']
        S10=['Classic Cars and Automobile Engineering','This detailed, illustrated book collection is a must-have reference guide for all owners of period automobiles, motorcycles, and anything powered by early 20th-century engines.cover everything that you ever wanted to know about' 
        +'the inner workings of antique cars, trucks, bikes, engines, tractors, and more']
        S11=['Molecular, Cellular, and Tissue Engineering','Known as the bible of biomedical engineering. Physiological modeling, tissue engineering, stem cells, drug delivery systems, artificial organs, and personalized medicine. More than three dozen specific topics are examined, including DNA vaccines.']
        S12=['Analysis and Application of Analog Electronic Circuits to Biomedical Instrumentation','It explains the function and design of signal conditioning systems using analog Ics―the circuits that enable ECG, EEG, EMG, ERG, tomographic images, biochemical spectrograms, and other crucial medical applications.It introduces the mathematical tools used to describe noise and its propagation through linear systems, and it looks at how signal-to-noise ratios can be improved by signal averaging and linear filtering.']
        S13=['Polymer Chemistry','A well-rounded and articulate examination of polymer properties at the molecular level, Polymer Chemistry focuses on fundamental principles based on underlying chemical structures, polymer synthesis, characterization, and properties. It emphasizes the logical progression of concepts and provide mathematical tools as needed as well as fully derived problems for advanced calculations.']
        S14=['Chemical Engineering Design','This new edition provides coverage of the latest aspects of process design, operations, safety, loss prevention, equipment selection, and much more, including updates on plant and equipment costs, regulations and technical standards.']
        S15=['Construction Project Scheduling and Control','Ensure successful construction projects through effective project scheduling and control The success of a construction project is dependent on a schedule that is well-defined yet flexible to allow for inevitable delays or changes.the analytical methods used to devise an efficient and successful schedule for construction projects of all sizes.']
        S16=['Introduction to Civil Engineering Systems: A Systems Perspective to the Development of Civil Engineering Facilities','This book presents an integrated systems approach to the evaluation, analysis, design, and maintenance of civil engineering systems. Addressing recent concerns about the world’s aging civil infrastructure and its environmental impact, the author makes the case for why any civil infrastructure should be seen as part of a larger whole.']
        S17=['Microbial Biotechnology in Environmental Monitoring and Cleanup','Pollutants are increasing day by day in the environment due to human interference. Thus, it has become necessary to find solutions to clean up these hazardous pollutants to improve human, animal, and plant health. Microbial Biotechnology in Environmental Monitoring and Cleanup is a critical scholarly resource that examines the toxic hazardous substances and their impact on the environment.']
        S18=['Environmental Engineering: Prevention and Response to Water-, Food-, Soil-, and Air-borne Disease and Illness','Environmental Engineering: Prevention and Response to Water-, Food-, Soil-, and Airborne Disease and Illness, Sixth Edition covers: Disease transmission by contaminated water Food-borne diseases Control of diseases of the air and land. Appropriate technology for developing countries Environmental emergencies and emergency preparedness.']
        S19=['Practical Electrical Engineering','This textbook provides comprehensive, in-depth coverage of the fundamental concepts of electrical engineering. It is written from an engineering perspective, with special emphasis on circuit functionality and applications. Reliance on higher-level mathematics and physics, or theoretical proofs has been intentionally limited in order to prioritize the practical aspects of electrical engineering.']
        S20=['Offshore Electrical Engineering Manual','The book begins with coverage of different types of insulation, hot-spot temperatures, temperature rise, ambient air temperatures, basis of machine ratings, method of measurement of temperature rise by resistance, measurement of ambient air temperature.']
        S21=['Mechanical Engineering for Makers: A Hands-on Guide to Designing and Making Physical Things','This practical, user-friendly reference book of common mechanical engineering concepts is geared toward makers who dont have (or want) an engineering degree but need to know the essentials of basic mechanical elements to successfully accomplish their personal projects.'
        +'Provides mechanical engineering information that includes math, science, physics and engineering theory without being a textbook']
        S22=['Shigley\'s Mechanical Engineering Design','Shigley\'s Mechanical Engineering Design is intended for students beginning the study of mechanical engineering design. Students will find that the text inherently directs them into familiarity with both the basics of design decisions and the standards of industrial components.']
        S23=['The Merck Manual of Diagnosis and Therapy','Packed with essential information on diagnosing and treating medical disorders, this comprehensive guide was written by a team of medical experts. This book is intended for everyday use by health care professionals for delivery of the best care to their patients.']
        S24=['Human Anatomy','Human anatomy is the study of the structures of the human body. An understanding of anatomy is key to the practice of medicine and other areas of health.']
        S25=['Nursing Diagnosis Handbook: An Evidence-Based Guide to Planning Care','This convenient handbook shows you how to correlate nursing diagnoses with known information about clients on the basis of assessment findings, established medical or psychiatric diagnoses, and the current treatment plan.']
        S=S1+S2+S3+S4+S5+S6+S7+S8+S9+S10+S11+S12+S13+S14+S15+S16+S17+S18+S19+S20+S21+S22+S23+S24+S25
        return S
    def RetCBooks():
        C1=['Business Statistics: Contemporary Decision Making by Ken Black','For Contemporary Decision Making helps students see the big picture of the business statistics course by giving clearer paths to learn and choose the right techniques. Tree Taxonomy Diagram for further illustrates the connection between topics and helps students pick the correct technique to use to solve problems. This books dives deep into understanding the basics of statistics, charts and graphs, descriptive statistics, probability, deriving inferences from data and building regression analysis and forecasting.']
        C2=['Business Statistics by JK Sharma','This edition of business statistics follows an easy-to-understand, problem-solving approach. Through detailed discussions on procedures that facilitate interpretation of data, this book enables readers to make more considered and informed business decisions. Using tools of application and practice in a variety of solved examples and practice problems, this book will sharpen the students understanding of basic statistical techniques. Help students suggest solutions to managerial issues using specific statistical techniques.']
        C3=['Tourism, Transport and Travel Management, M. R. Dileep','This comprehensive textbook provides students with essential knowledge of the intricate relationship existing between travel, transport and tourism. The book analyses the structure, functions, activities, strategies and practices of each of the sectors in the travel industry, such as airlines, airports, tour operators, travel agencies and cruises. It is structured into six parts, covering all modes of transport (air, land and water), travel intermediation, the tour operation business and impacts and prospects for the future. International case studies are integrated throughout to showcase practical realities and challenges in the travel industry and to aid students’ learning and understanding.']
        C4=['Tourism Economics and policy, by Larry Dwyer & Peter Forsyth','Tourism Economics and Policy combines a comprehensive treatment of economic concepts and applications in tourism contexts. The topics covered are those that most occupy the attention of tourism economists in research and policy areas internationally. Content includes tourism demand and forecasting; tourism supply and pricing; measuring tourism\'s economic contribution using tourism satellite accounts; measuring the impacts and benefits of changes in tourism demand, contrasting Input-output and computable general equilibrium modelling']
        C5=['International Finance, Transactions, policy and regulations by Hall scott, Anna Gelpern','This textbook provides comprehensive coverage of international finance from policy, regulatory, and transactional perspectives.the infrastructure of global financial markets, including payment, clearing and settlement systems, foreign exchange regimes, and international coordination of capital and liquidity requirements.']
        C6=['Management Accounting by Greg Sheilds','Through management accounting, you can create forecasts for the future, make smart buying decisions, analyze the rate of return on an investment and much more. Management accountants do a lot when it comes to the management aspect of running a business.Some of the topics that are discussed in this book: Management Accounting and Its Importance Management Accounting Principles Responsibility Accounting Understanding and Managing Costs Budgeting Like a Pro Forecasting Tools for Business Trends Theory of Constraints Careers in Management Accounting And much more.']
        C7=['Marketing Management by Philip Kotler','Marketing management book dives into the depths of understanding how to stay in the cutting edge in the dynamic world of marketing. This tackles core issues on connecting with customers, building strong brands, shaping the market offerings, delivering value, communicatiang value and finally creating long term successful growth. Other core aspects of marketing discussed in this book include Conducting Marketing Research and Forecasting Demand, creting customer value satisfaction & loyality, analysing consumer & business markets, creating with brad equity and effectively dealing with competition.']
        C8=['Marketing Management Strategy by Peter Doyle','Marketing Management and Strategy is a concise and practical management guide to the latest ideas in advanced Marketing and Strategy. It shows you how to develop a marketing orientation in the organisation and how this impacts on the ultimate corporate goals of profit, growth and security. They then examine how marketing strategies are developed and implemented through effective product, pricing, distribution, communication and services.']
        C9=['An Introduction to Banking: Principles, Strategy and Risk Management by Moorad Choudhry','This books is a coprehensive guide to understanding hte cruical aspects of bank business and markets, asset liability management and liquidity risk. It also teaches strategies requred to thrive in the marketplace. A key role for a bank is to transform short-term deposits from businesses and households into long-term loans to businesses and households that want to borrow for investments or consumption.']
        C10=['Financial Risk management by Don M Chance','This book levels the playing field by approaching risk management from the buy side instead, focusing on educating corporate and institutional users of risk management products on the essential knowledge they need to be an intelligent buyer. Rather than teach financial engineering, this volume covers the principles that the buy side should know to enable it to ask the right questions and avoid being misled by the complexity often presented by the sell side.']
        C11=['Accounting Principles by Jerry J weygandt and Paul D Kimmel','Accounting principles will help you understand the essential financial components of businesses, Whether you are looking at a large multinational company like Apple or Starbucks or a single-owner software consulting business or coffee shop, knowing the fundamentals of accounting will help you understand what is happening.']
        C12=['Financial accounting and accunting standards by kieso Weygandt','Financial accounting approaches teaching accounting from a bottom up fasion by tackling concepts like Event, Transaction, Account, Real Account, Nominal Account, Ledger, Journal, Posting, Trial Balance, Adjusting Entries, Financial Statements, Closing Entries. You will clearly understand the basic accounting terminology, explain steps in the accuoting cycle, explaiun double entry rules, record transactions in journal, prepare financial statements from the adjusted trial balance and prepare closing entries.']
        C13=['Taxation, A very short introduction by Stephen Smith','This simple book gives information regarding who must pay taxes, the structure of taxation, who would bear the tax burden, taxation in relation to the economy, taxation evasion and enforcement and finally the issues in the tax policy.']
        C14=['Principles of Business Taxation by David Gibberman','Accounting principles will help you understand the essential financial components of businesses, Whether you are looking at a large multinational company like Apple or Starbucks or a single-owner software consulting business or coffee shop, knowing the fundamentals of accounting will help you understand what is happening.']
        C15=['Applied Economcs: A Practical Guide by Chung Ki Ming','Applied Econometrics: A Practical Guide is an extremely user-friendly and application-focused book on econometrics. This book is perfect for beginners and promises simplicity and practicality to the understanding of econometric models. Written in an easy-to-read manner, the book begins with hypothesis testing and moves forth to simple and multiple regression models.This integration of published articles helps the readers to understand how econometric models are applied to real-world use cases']
        C16=['Applied INternational Economics: W Charles sawyer and Richard S sprinkle','Applied International Economics, offers a modern and accessible treatment of international economics, shifting the emphasis from pure theory to the application of theory by using the standard tools of economic analysis.']
        C=C1+C2+C3+C4+C5+C6+C7+C8+C9+C10+C11+C12+C13+C14+C15+C16
        return C
    def RetHBooks():
        H1=['Linguistics and English Literature by HD Adamson','Concise and engaging, this textbook introduces stylistics, the application of linguistics to literary analysis. Assuming no prior knowledge of linguistics, H. D. Adamson discusses linguistics before addressing its application to literature, enabling students to become knowledgeable in both fields. The book covers a wide range of topics in linguistics and literary criticism, as well as a variety of literary genres and popular culture, from poems and contemporary literature to comic book art and advertising.']
        H2=['Studying English Literature and Language by Rob Pope','Studying English Literature and Language is unique in offering both an introduction and a companion for students taking English Literature and Language degrees. Combining the functions of study guide, critical dictionary and text anthology, this is a freshly recast version of the highly acclaimed The English Studies Book. The features include fresh sections on the essential skills and study strategies needed to complete a degree in English―from close reading, research and referencing to full guidelines and tips on essay-writing, participating in seminars, presentations and revision an authoritative guide to the life skills.']
        H3=['Elements of Indian Art: Including Temple Architecture, Iconography and Iconometry by Swaraj Prakash','The work studies basic principles of ancient India art and architecture. It deals with Hindu thinking and practice of art including the Hindu view of Godhead, iconography and iconometry and symbols and symbolism in Hindu art.']
        H4=['The history of Indian Art, by Anil Rao ,Sandhya Ketkar ','Prehistoric Period, the Indus Valley Civilization, Vedic Period – Indo-Aryan Art, Art in the times of Buddha, the Shunga and Kanva Period, the Kushan Age, the Andhra Period, the Gupta Era, the Pre-medieval Era, Late middle Age, Jain and Rajput Miniature Art Styles, Art in the Sultan Era and Art in the Modern Era.']
        H5=['Strategic Mnagement and Business Policy by Thomas L Wheelen','This books formulates the essentials on strategizing the business policy by introducing you to various techniques and methods. The most inportant of them being Strategy Formulation, Strategy Formulation, Strategy Implementation and Control, case analysis and other strategic issues.']
        H6=['Business Policy and strategic Management by Francis Cherunilam','This book elucidates the importance of the Social, Environmental and Economic Responsibilities of Business, Corporate Governance, Business Environment, Environmental Forecasting and Analysis, SWOT Analysis and Strategy Formulation.']
        H7=['Law of contract and specific relief by Dr. Avtar Singh','The book deals with the intricacies of contract law in a straightforward and lucid style. The book covers many new developing areas in contract law which are of practical and academic importance. The book covers recent decisions on issues arising out of modern day trade and commerce, which have thereby contributed to the development of the law on the subject.']
        H8=['International Law by Gurdeep Singh','International Law by Gurdip Singh provides an authoritative and stimulating overview of this important subject, revealing international law in its full diversity.International Court of Justice, United Nations, peacekeeping perations, compulsive methods: short of war, war, economic warfare, nuclear warfare, star wars, implementation of human rights and International Criminal Court.']
        H9=['Handbook of Journalism and Mass Communication by VS Gupta, Vir Bal AGARWAL','The book has been split into six distinct portions, which focus on important topics pertaining to this field.Media Management, Public Relations, Electronic Media, Theories and Indian Communication Landscape, Public Relations and Advertising, and Mass Communication – Origin and Development are the titles of the six portions that this book has been divided into.']
        H10=['Mass communication in INdia, Keval j kumar','a general introduction to communication theory.journalism, radio, television, cinema, advertising, public relations, folk media and group media.the psychology and sociology of the audience.The Effects of the Mass Media']
        H11=['The fundamentals of fasion design by Richard Sorger','This book offers an introductory look at fashion design--with a sophisticated twist. Sections include Pattern Construction and Cutting, Fashion Movements, Textiles, Creative Thinking, and Selling Clothes. With exciting visuals and clear text, The Fundamentals of Fashion Design uses detailed diagrams, historical references, and innovative layout to challenge readers to consider the underlying principles of design.']
        H12=['Fashion Design Course: Principles, Practice, and Techniques: The Practical Guide for Aspiring Fashion Designers by Steven Faerm','The book opens with an overview of the principles of fashion design, a survey of the industry\'s history and its key designers, and a description of today\'s markets and customers. The tutorials that follow instruct in designing sportswear, tailored garments for wear to business careers, denim/activewear, cocktail and evening wear, children\'s clothing, men\'s garments, and accessories.']
        H13=['Hotel Management and operations by Michael J. O\'Fallon, Denney G. Rutherford','a variety of viewpoints on the duties, responsibilities, problems, and opportunities encountered there.  Multidimensional case studies, taking a practical approach, challenge readers  to identify the central issues involved in complex management problems, understand the structure and resources of the department in question, and find solutions that may help in managing other hotel resources and departments.']
        H14=['Hotel Operations Management by David Hayes','Hotel Operations Management provides an up-to-date and comprehensive examination of all aspects of hotel administration from the viewpoint of the hotel general manager. Detailed information addresses the operating departments of a full-service hotel: Human Resources; Controller; The Front Office; Housekeeping; Food and Beverage; Safety and Property Security; Sales and Marketing; Accounting; and Facility Engineering and Maintenance.']
        H=H1+H2+H3+H4+H5+H6+H7+H8+H9+H10+H11+H12+H13+H14
        return H



